# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# 修改此全局配置文件后,需要运行 rails app:config 或手动复制并覆盖 config/application.yml
APP_NAME: '商城'
ADMIN_NAME: '管理系统'
PER_PAGE: '1'
SECRET_KEY: 'www.mall.cycle.com'

# WeChat
SECRET_KEY_BASE: 7e87f04b602540188357f8b579701d4cdb8a02f2ebe6624af13511083baf39e02306911690a6a828601e81c0d8efde5fc952d8a0c496aedac1af76cc58c11c29
WX_APP_ID: wx8d767408f4733f80
WX_APP_SECRET: 3cf0272e857e1cc4df674701a089cdb0
WX_GRANT_TYPE: authorization_code

# Qiniu
QINIU_ACCESS_KEY: 'ttBdVzznFEazytbwWBqoHUwRKCFPo3osakSGg5Nv'
QINIU_SECRET_KEY: 'ExLSnZ1Z-KOGV5Qt_4EAw0gt45fkcBojBNX0jzw2'
BUCKET_NAME: 'wxshopadmin'
QINIU_HOST: 'p7dorcp13.bkt.clouddn.com'

DATABASE_NAME: wxshopadmin
DATABASE_USERNAME: root
DATABASE_PASSWORD: 123abc..

development:
  DATABASE_NAME: wxshopadmin-dev
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: 123abc..

test:
  DATABASE_NAME: wxshopadmin-test
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: 123abc..

production:
  DATABASE_NAME: wxshopadmin-pro
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: 123abc..